### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by codepathreview** [deepmehtait/To-Do-Android-Material#1]
Hello Deep, 

Looks great, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

Great to see you were able to complete a large number of extensions to your app already. Your project looks great. As you can probably tell, the extension tasks available on each project are the valuable learnings since they dive deeper into common real-world Android use cases. 

Be sure to take a look through our [organizing your source files guide](http://guides.codepath.com/android/Organizing-your-Source-Files#android-folder-structure) for tips on organizing your code as well.

Now that you've completed the pre-work, we'll be following up with you again shortly to outline the next steps in the admissions process.

**Comment by deepmehtait** [comment]
@codepathreview When do you plan to follow up?

**Comment by nesquena** [comment]
Very soon, sorry for the delay!

**Comment by codepathreview** [comment]
Hello Deep,

Great to see you were able to augment your app with many extensions now. As mentioned earlier, the extension tasks available on each project are often the most valuable learning since they dive deeper into common real-world Android use cases.

We'll be in touch with you again soon via email. Let us know if you have any questions about the project or anything in the meantime, you can always reach us at <admissions@codepath.com>.

**Comment by nesquena** [comment]
Hi Deep,

I appreciate your interest in the course and your work on the pre-work. I hope you can participate in a future cohort!
